### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by hitbg-yjm** [KIT-ISAS/lili-om#11]
ubuntu18.04 gtsam 4.00 ceres 2.00 Eigen 3.3.4
Is Eigen version not matching?   Thanks!
![Screenshot from 2020-12-15 09-13-15](https://user-images.githubusercontent.com/64351196/102155103-cb8dc280-3eb5-11eb-825f-8804fc065922.png)

usr/local/include/ceres/jet.h:998:8: error: ‘ScalarBinaryOpTraits’ is not a class template
 struct ScalarBinaryOpTraits<ceres::Jet<T, N>, T, BinaryOp>

**Comment by limeng1523** [comment]
Hi @hitbg-yjm,
I recommend you to use the latest version of Eigen. And it's better to make sure whether your ceres has been successfully installed. You could first install the latest version of Eigen and then reinstall ceres. I hope this will help you.
