### ISSUE TITLE
Inconsistent performance from different start timestamp using the same dataset

### ISSUE THREAD

**Issue by tanmengwen** [KIT-ISAS/lili-om#12]
Hi kailaili,
Thanks for your good work!

I compiled and ran this project with the given datatset, for example FR_IOSB_Tree_64.bag.
It was working well when i played the rosbag from the begin time. But it drifted quite a lot when i played the rosbag from a later timestamp such as from 30s.

I didn't know what reason caused this result. I guess maybe it should start with static status. Looking for forward your reply.
Thank you!

![image](https://user-images.githubusercontent.com/8319316/102475805-4eb93f00-4095-11eb-9b51-a491e8bec522.png)

**Comment by kailaili** [comment]
![Screenshot from 2020-12-17 12-47-09](https://user-images.githubusercontent.com/30347709/102484074-00407c00-4066-11eb-8274-aa28f5acdaa3.png)

Hi, above is the result from running lili_om_rot on this sequence. There shouldn't be a problem. Maybe you should check whether you used the right launch file (run_fr_iosb.launch).

**Comment by tanmengwen** [comment]
Hi kailaili,

I'm sure I used the right launch file(run_fr_iosb.launch). 
I could also get abover result same as you when play the rosbag from the start timestamp.  

I mean lili_om_rot would drift, for example, just use the command below to jump the head 30s. 
rosbag play FR_IOSB_Tree_64.bag -r 1.0 --clock  -s 30

**Comment by kailaili** [comment]
Apparently you need to have a proper initialization of the IMU. The current one initializes the IMU given a static state.
