### ISSUE TITLE
errors with own datasets

### ISSUE THREAD

**Issue by YushengWHU** [KIT-ISAS/lili-om#14]
Hello here, I tried to evaluate ur tightly coupled system with my loosely coupled algorithm, but the back-end optimization process of ur algorithm always crashes after a while, some times only a couple of seconds, with the output:
![Screenshot from 2020-12-20 17-21-51](https://user-images.githubusercontent.com/40022787/102709873-583ae500-42e9-11eb-979b-739e4b1ede82.png)
I chose several scenarios for comparison with ur algorithms:
The first is the common school scene, where the map output crashed **whenever my robot start moving**, which seems to be wrong coordinates setup, (I also encountered the same situation when testing _LIO-SAM_) however, I have  exactly the same coordinate definition in my second scenario, which seems fine at first.
![Screenshot from 2020-12-20 17-22-27](https://user-images.githubusercontent.com/40022787/102709925-abad3300-42e9-11eb-858d-371f1d788e47.png)
**Figure 1.** Everything seem fine at first in school scene
 
![Screenshot from 2020-12-20 17-23-07](https://user-images.githubusercontent.com/40022787/102710145-540fc700-42eb-11eb-9a82-dbfded9ec4ee.png)
**Figure 2.** Whenever the robot starts moving, the back end fusion crashes

The second is the railway scene, the back-end optimization seems to work **longer** now, but it still keeps crashing from time to time.
![Screenshot from 2020-12-20 11-29-45](https://user-images.githubusercontent.com/40022787/102710077-c59b4580-42ea-11eb-8b23-5c68f2c42f05.png)

**Hardware setup:
MTI680g(forward-left-up), livox horizon(forward-left-up).**

**I only used mti680G IMU for preprocessing and backend fusion.**

Do you have any suggestions?

**Comment by YushengWHU** [comment]
By the way, everything is fine with ur datasets, and my algorithm can work on ur datasets without any modification, which is to say, we have the same coordinate definition.

**Comment by kailaili** [comment]
I don't really get what you mean. You seemed to be using the backend of lili-om with your loosely coupled as the frontend? Or just wanted to compare the two systems? In general, those parameters should be retuned depending on your own sensors, motion and the deployed surroundings. Also, you may need to take a look at orientation initialization of your own system.  We tested lili-om also live with pedestrian-like motion and urban scenario and the system worked fine. Without much more insight into your own system setup we are not able to give specific solution for deploying lili-om on your own platform.

**Comment by YushengWHU** [comment]
> I don't really get what you mean. You seemed to be using the backend of lili-om with your loosely coupled as the frontend? Or just wanted to compare the two systems? In general, those parameters should be retuned depending on your own sensors, motion and the deployed surroundings. Also, you may need to take a look at orientation initialization of your own system. We tested lili-om also live with pedestrian-like motion and urban scenario and the system worked fine. Without much more insight into your own system setup we are not able to give specific solution for deploying lili-om on your own platform.

Actually, I want to compare the performance of your algorithm with my own, my algorithm works fine on your datasets, which is to say, we have the same hardware coordinates definition. The problem is, when I apply your algorithm on my own datasets, the back end fusion of your algorithm always  crashes after a while, for better description, below is two example of my testing scenes.
I used multiple livox horizons for my algorithm (5-8) and I only choose the front one for applying your algorithm.
![Screenshot from 2020-12-19 16-25-54](https://user-images.githubusercontent.com/40022787/102710562-0ea0c900-42ee-11eb-8310-ef8b219fe93b.png)
**Figure1.** School scene
![Screenshot from 2020-11-17 20-31-30](https://user-images.githubusercontent.com/40022787/102710593-40b22b00-42ee-11eb-95df-7d08aa2ebf03.png)
**Figure 2.** railway highspeed scene

**Comment by kailaili** [comment]
The scene should be applicable for lili-om.  However, you have a different sensor setup which definitely requires retuning of the parameters.

**Comment by YushengWHU** [comment]
The problem here is the tiny difference between MTI 680G and MTI670, although they have the same coordinate definition, the output is slightly different. 
![xti670_livox_angular_velocity](https://user-images.githubusercontent.com/40022787/104330937-7b903300-5529-11eb-9f46-09e0a7635b7b.jpg)
![xti670_livox_linear_acc](https://user-images.githubusercontent.com/40022787/104330943-7d59f680-5529-11eb-8fc5-02eef1e4a5cb.jpg)
![xti680_livox_angular_velocity](https://user-images.githubusercontent.com/40022787/104330947-7df28d00-5529-11eb-924e-81ba757fb767.jpg)
![xti680_livox_linear_acc](https://user-images.githubusercontent.com/40022787/104330949-7e8b2380-5529-11eb-9a05-71e88fb4cbcb.jpg)
As you can see, the **X** and **Y** coordinates of MTI 670 is the opposite to livox IMU, while the MTI 680 has the same trend with livox IMU.
After changing **angular velocity** and  **linear acceleration** x and y to negative, everything works fine.
