### ISSUE TITLE
Loop detection

### ISSUE THREAD

**Issue by Zale-Liu** [KIT-ISAS/lili-om#18]
I am curious about your loop detection module, while you did not mention it in your paper. So I want to know how your loop-detection module work? Which paper or website can I refer to?

**Comment by kailaili** [comment]
Hi, there will be an update of the paper coming soon. Otherwise it's a typical ICP-based approach with loop closures searched in both spatial and temporal domains. The corresponding code can be found in the backend fusion module.

**Comment by Zale-Liu** [comment]
Thank you very much. I am reading your code and feel confused of some codes. I look forward to your updated paper.
