### ISSUE TITLE
Jumping points in the trajectory when running Example for lili_om (Livox Horizon)

### ISSUE THREAD

**Issue by Flandoe** [KIT-ISAS/lili-om#21]
I followed the usage steps to run the Example for lili_om (Livox Horizon), but there were some jumping points in the trajectory. What is the reason may causing the problem? Thanks.
![image](https://user-images.githubusercontent.com/10720908/106688329-db4d9b80-6608-11eb-9340-ef469250c416.png)

**Comment by kailaili** [comment]
We don't observe such an issue running that sequence. But this looks to be some nonconvergence at backend due to insufficient processing speed. You may tune the parameters to fuse fewer features according to your hardware or try rerunning the data set.
