### ISSUE TITLE
There was a problem running FR_IOSB_Short_64 data

### ISSUE THREAD

**Issue by Soverngity** [KIT-ISAS/lili-om#22]
Hello, author. I have seen your work and I think it is excellent.
But when I configured the environment and tried to run the code using the data you provided, the following error occurred.
![微信图片_20210205230248](https://user-images.githubusercontent.com/42853085/107050527-4ca66d80-6806-11eb-8baa-fdf8eb3381d2.png)

**Comment by kailaili** [comment]
![Screenshot from 2021-02-05 16-42-44](https://user-images.githubusercontent.com/30347709/107055114-3f22c080-67d1-11eb-85b8-327376e55a89.png)
We don't see this issue with running this sequence. Perhaps you could take a look whether your dependencies were correctly installed.
