### ISSUE TITLE
the codes crashed down when running VLP16 and mti300 in winding mountain road

### ISSUE THREAD

**Issue by yandiyang** [KIT-ISAS/lili-om#23]
![Screenshot from 2021-02-06 10-12-41](https://user-images.githubusercontent.com/55324884/107105959-07b12400-6864-11eb-87a0-9177b817d2cf.png)

It works well at first, any possible reasons? Appreciate it!

**Comment by kailaili** [comment]
Please check your hardware and tune the parameters accordingly.
