### ISSUE TITLE
There are some problems in the initial trajectory of rotating lidar data

### ISSUE THREAD

**Issue by Soverngity** [KIT-ISAS/lili-om#25]
Hello author, thank you for your work.
When I was running my own pandar40 data, there was such a problem with the initial trajectory point in rviz.
![2021-02-17_22-47](https://user-images.githubusercontent.com/42853085/108220998-48694100-7172-11eb-9f3b-549939a07c31.png)

**Comment by kailaili** [comment]
We didn't test lili-om on Pandar40. There could be many reasons for such an effect. You may check you own definition of coordinates, your calibrations, and tune the parameters accordingly.

**Comment by Soverngity** [comment]
Dear author, I solved the above problem because of the acceleration of gravity.
But now I have another problem, as shown in the figure.The code runs normally in the previous period of time, but every time it runs for a long time, the system will report an error. It seems to be the problem of Ceres error term. Do you have any opinion about it?
![2021-03-18_16-04](https://user-images.githubusercontent.com/42853085/111592921-5effc800-8804-11eb-99e2-3753b861f226.png)

**Comment by Soverngity** [comment]
@kailaili
