### ISSUE TITLE
Saved pcd map is less dense then the global map in Rviz

### ISSUE THREAD

**Issue by spajder16** [KIT-ISAS/lili-om#26]
Hi,
I would like to make a dense 3D map with lili-om, but the saved point cloud has fewer points than the global map in Rviz.
![pointclouds_comparation](https://user-images.githubusercontent.com/9286759/110447655-b85b4f00-80c0-11eb-9f8d-1cfd8b313455.jpg)

 Also, could you tell me how to get the denser map? When I set mapping_ds less than 0.1 I get the warning:
 "[pcl::VoxelGrid::applyFilter] Leaf size is too small for the input dataset. Integer indices would overflow." but still the map are built ok. Is it possible to set the algorithm to process the downsampled point cloud and build the map with a full point cloud scan?

**Comment by kailaili** [comment]
Hi, it may help if you play your bag file at a lower frame rate with lower downsampling ratio and shorter mapping interval.
