### ISSUE TITLE
Use Livox Avia

### ISSUE THREAD

**Issue by duanqg** [KIT-ISAS/lili-om#27]
Good job！
Can I use Livox Avia to run the code？

**Comment by kailaili** [comment]
For the repetitive line scanning of Livox Avia, the system should be applicable given proper tuning of parameters. (We didn't test it yet).

**Comment by duanqg** [comment]
@kailaili 
thank you
Is the avia Non-repetitive Circular Scanning pass your test？
Do the parameters need to be changed？
thank you！

**Comment by duanqg** [comment]
Dear Brother Li，I would like to use the non-repeated scanning of Livox Avia
to carry out SLAM of lili. Can I achieve the same effect as Livox Horizon?
If debugging changes are made, where should I make the changes?

在 2021年4月29日星期四，Kailai Li ***@***.***> 写道：

**Comment by kailaili** [comment]
The system was not tailored for the scan pattern of circular shape. One could replace the feature extraction module with the one from loam_livox or something similar.

**Comment by duanqg** [comment]
感谢您！我使用livox avia有了很好的结果，应该是可以适配的。
但是由于MTI680G的原因，出现了拐弯部分飞起偏移的情况，这个在horizon和avia上都出现了。
然后看到了这个issue，https://github.com/KIT-ISAS/lili-om/issues/14，和我的问题一模一样，请问按照这篇文章所说的imu的angular velocity and linear acceleration x and y 在代码的哪个部分改动?

**Comment by bugdeveloper0** [comment]
> 

@duanqg 哥们，你现在可以跑适配avia的包了吗

**Comment by aiqibaobei** [comment]
@bugdeveloper0  我尝试了自己录的avia包，可以跑的，但是因为作者的代码需要两个imu，用那个internal launch应该就可以了
