### ISSUE TITLE
which ceres2.0 to build 

### ISSUE THREAD

**Issue by narutojxl** [KIT-ISAS/lili-om#3]
Hi  @kailaili,
Which version of ceres2.0 we need to build from source firstly? Theres are 3 versions: `2.0.0rc1`, `2.0.0rc2`, `2.0.0`,  [link is here](https://github.com/ceres-solver/ceres-solver/tags), thanks for your help!
Best

**Comment by kailaili** [comment]
Hi, just build it from source as the link gives. That's the latest stable version 2.0.0
