### ISSUE TITLE
Long build times for BackendFusion target

### ISSUE THREAD

**Issue by mbcel** [KIT-ISAS/lili-om#30]
I want to try out some minor changes in the BackendFusion.cpp file. However for every change the incremental build/compile time takes more than 1 minute on my i5 9300HF cpu. I am wondering if you also experience these long build times or if you set some cmake flags during development to overcome this very long build time?

I also tried out the `ninja` generator instead of `make ` with minor successes which reduced the compile time from 1 min 30 secs to still around 1 min 15 secs

**Comment by kailaili** [comment]
It's quite typical time duration for building such systems.
