### ISSUE TITLE
Not enough feature points from the map

### ISSUE THREAD

**Issue by David9696** [KIT-ISAS/lili-om#32]
Hi,

Thanks for sharing this great package.

When I tried to regenerate your result by using livox horizon and xsens imu, I got this warning message:

"Not enough feature points from the map"

May I know what is the problem?

Thanks

**Comment by kailaili** [comment]
Hi, this depends on the threshold that is set for the amount of feature points that are involved for computation.
Since it's a global threshold, there could be such warning for some frames.
