### ISSUE TITLE
Backend fusion dying

### ISSUE THREAD

**Issue by JasperTan97** [KIT-ISAS/lili-om#33]
I have tried the given datasets for the velodyne version of lili-om and it works.

When I run my own dataset, this occurs. Does anyone know what this means? For reference, the dataset I use is the park dataset from [lio-sam](https://github.com/TixiaoShan/LIO-SAM).

> BackendFusion: /usr/include/boost/smart_ptr/shared_ptr.hpp:734: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = const sensor_msgs::Imu_<std::allocator<void> >; typename boost::detail::sp_member_access<T>::type = const sensor_msgs::Imu_<std::allocator<void> >*]: Assertion `px != 0' failed.

For reference, my yaml file is as follows:

common:

>   frame_id: "lili_om_rot"
>   data_set: "Park"
>   
> IMU:
>   acc_n: 3.9939570888238808e-03
>   gyr_n: 1.5636343949698187e-03
>   acc_w: 6.4356659353532566e-05
>   gyr_w: 3.5640318696367613e-05
> 
> preprocessing:
>   lidar_topic: "/points_raw"
>   ds_rate: 4
>   line_num: 16
> 
> lidar_odometry:
>   max_num_iter: 12
>   scan_match_cnt: 1
>   if_to_deskew: false
> 
> backend_fusion:
>   max_num_iter: 15
>   loop_closure_on: true
>   local_map_width: 50
>   lc_search_radius: 15
>   lc_map_width: 25
>   lc_icp_thres: 0.2
>   slide_window_width: 3
>   imu_topic: "/imu_correct"
>   lidar_const: 7.5
>   mapping_interval: 2
>   lc_time_thres: 60.0
>   surf_dist_thres: 0.12
>   kd_max_radius: 1.0
>   save_pcd: false
> 
> #extrinsic imu to lidar
>   ql2b_w: 0
>   ql2b_x: 1
>   ql2b_y: 0
>   ql2b_z: 0
> 
>   tl2b_x: 0.0
>   tl2b_y: 0
>   tl2b_z: 0.0

Thanks everyone!

**Comment by Bazinga92445** [comment]
Hi, have you solved this problem eventually? It also occurred when I ran lili_om on  KA_Urban_East.

**Comment by JasperTan97** [comment]
No. I am sorry.

**Comment by xingyuuchen** [comment]
Hi, I also encounter the same question.

**Comment by xingyuuchen** [comment]
Hi, you can see more details of the crash using gdb core dump.
