### ISSUE TITLE
[Question] How did you time synchronise the IMU & Lidar?

### ISSUE THREAD

**Issue by seajayshore** [KIT-ISAS/lili-om#37]
Sorry if this is written somewhere and I just didn’t see.

How are you achieving good synchronisation between the IMU data & Lidar?
A PPS output from the IMU? Do you use GPS clock source?

**Comment by kailaili** [comment]
Hi, we used PTP for the synchronization. One possible solution can be found here: https://github.com/ptpd/ptpd

**Comment by seajayshore** [comment]
Ah, but PTP makes sense for the Lidar & system.
But the MTI-670 IMU has no PTP capability right? How did you synchronise that?

**Comment by kailaili** [comment]
The IMU data is synchronized using the GPS channel onboard

**Comment by seajayshore** [comment]
Great, thanks for confirming! :-)

**Comment by asteppke** [comment]
A quick follow-up on the same topic: the Livox Lidar has different synchronization options, here PTP can be used to synchronize Lidar <-> PC clock. The MTI-670 IMU uses a GPS receiver on the development board, which allows to synchronize IMU <-> GPS. 

How is the remaining synchronization between PC clock <-> IMU/GPS achieved? 
Thank you for any insights.
