### ISSUE TITLE
about the scanID in Preprocessing

### ISSUE THREAD

**Issue by CanCanZeng** [KIT-ISAS/lili-om#39]
Hi @kailaili , is the scanID here https://github.com/KIT-ISAS/lili-om/blob/6cdf4405bc51543f0a8a7f0ef94b06d61ce44adb/LiLi-OM-ROT/src/Preprocessing.cpp#L326 important? I guess you use this method to compute the ring number of a laser scan, but acctually my velodyne VLP-32C lidar has uneven scan lines, there is a map between ring number and vertical angle according to the manual in https://icave2.cse.buffalo.edu/resources/sensor-modeling/VLP32CManual.pdf page 57.
![image](https://user-images.githubusercontent.com/26817559/124768376-334b4e00-df6b-11eb-9c2a-cfafaf3cfac4.png)

I'm trying to use this map for vertical angle and scanID transform.
Please let me know if I misunderstand the code, thank you!

**Comment by kailaili** [comment]
Hi, the current preprocessing is only for rotational lidar with even scan line interval. In your case that part needs to be tailored according to your own hardware.
