### ISSUE TITLE
Robustness at higher speed

### ISSUE THREAD

**Issue by KarlssonW** [KIT-ISAS/lili-om#44]
Hello, i have tried LiLi-OM on some datasets and it seems very robust, though for my application we will use it on vehicles that might move at up to 70km/h.

Do you know how fast a Vehicle can go before the mapping becomes unreliable? So far we dont have any high velocity datasets to test this on our own.

Thanks!

**Comment by kailaili** [comment]
Hi, we didn't test the system for that speed. The fastest speed we've tried would be around 3-4 m/s. For deployment to real vehicles, you may take a look at https://github.com/Livox-SDK/LIO-Livox from Livox, which also refers to our system.
