### ISSUE TITLE
parameter tuning

### ISSUE THREAD

**Issue by bugdeveloper0** [KIT-ISAS/lili-om#46]
hi, i am troubled in getting the desired result from your code and dataset. what parameters should i tune in run_fr_iosb_internal_imu.launch and config_fr_iosb_internal_imu.yaml when playing FR_IOSB_Short.bag. The end-to-end error in your paper is 0.25 m or lili-om, but i have the result about 2m. looking forward to your reply!

**Comment by kailaili** [comment]
Hi, *_fr_iosb_internal_imu.yaml is for the internal IMU, whereas the one in the paper refers to an external IMU (MTi-670).  Apparently one could expect that the performance of the internal IMU is worse than the external one.

**Comment by bugdeveloper0** [comment]
thank you for your reply. It fails when i play other bagfiles such as hku campus provided by hku mars lab. what should i do to make the program work normally for other recorded bagfile?



---Original---
From: "Kailai ***@***.***&gt;
Date: Thu, Jan 20, 2022 16:42 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [KIT-ISAS/lili-om] parameter tuning (Issue #46)




 
Hi, *_fr_iosb_internal_imu.yaml is for the internal IMU, whereas the one in the paper refers to an external IMU (MTi-670).  Apparently one could expect that the performance of the internal IMU is worse than the external one.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kailaili** [comment]
Usually the calibration should be renewed, and some further tuning of the parameters is essential.

**Comment by bugdeveloper0** [comment]
is the program already compatible with avia?



---Original---
From: "Kailai ***@***.***&gt;
Date: Thu, Jan 20, 2022 16:57 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [KIT-ISAS/lili-om] parameter tuning (Issue #46)




 
Usually the calibration should be renewed, and some further tuning of the parameters is essential.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
