### ISSUE TITLE
Info: using with RealSense L515

### ISSUE THREAD

**Issue by quizzy5889** [KIT-ISAS/lili-om#6]
Hello to all,
First of all congratulations for your interesting work. I have read papers and documentation and would like to try your technique for indoor mapping using the Realsense L515 lidar.

What do you think about it? Do you see complications in using this hardware?

**Comment by kailaili** [comment]
Hi, thank you for your interest in the work. 

We didn't try with LiDAR for indoor use. To use LiLi-OM with Realsense L515 you would definitely need to change the feature extraction part in the preprocessing module. The backend fusion module should be in general applicable. Then tuning the parameter is also required as the current system uses LiDAR for outdoor scenario (with max range of more than 200m). 

For feature extraction, you may consider some appearance-based local descriptor as the Realsense one provides both depth and RGB images. However, those classic works designed for RGB-D odometry would be more directly applicable. 

You are more than welcome to try LiLi-OM out with devices of very different types and we look forward to your new report.
