### ISSUE TITLE
publish odometry

### ISSUE THREAD

**Issue by narutojxl** [KIT-ISAS/lili-om#8]
Hi all,
When we publish odometry, the published pose's time is last keyframe's time in the current window, but the pose is the first keyframe in the current window. 
https://github.com/KIT-ISAS/lili-om/blob/4ab3639cbfd58a7f3aa1bde5f8277d2c64579076/LiLi-OM-ROT/src/BackendFusion.cpp#L2136-L2147
It maybe a typo, should be `odom_mapping.pose.pose.orientation.w = pose_info_cloud_frame->points[pose_info_cloud_frame->points.size() - 1].qw;` ? Thank for your help!

**Comment by kailaili** [comment]
I don't think so.
